[project]
name = "pytorch-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.3",
    "pre-commit>=4.3.0",
    "torch>=2.8.0",
    "transformers>=4.57.1",
]
